-- Verifica email in fase di REGISTRAZIONE (OTP): una riga rappresenta una registrazione pendente.
-- I dati del form restano qui finché il codice non viene verificato; alla verifica corretta si crea
-- l'utente vero (tabella "user") e la riga viene consumata. A differenza di login_otp (legato a un
-- id_user esistente) qui l'utente non c'è ancora, quindi la chiave logica è l'email.
--
-- password_hash e code_hash sono BCrypt (mai in chiaro, nemmeno per dati non ancora verificati).
-- Validità tipica 5 minuti (stesse impostazioni otp.* del login).
--
-- Schema gestito a mano (spring.sql.init.mode=never, niente Flyway): esegui questo script
-- nello SQL Editor di Supabase, sul progetto a cui punta l'app.
--
-- Surrogate key bigint + UNIQUE su email (come login_otp: id + UNIQUE su id_user): un solo pending
-- per email, e il RegistrationService fa delete-then-insert per evitare l'ambiguità insert/update
-- di Spring Data JDBC con chiavi naturali.
CREATE TABLE IF NOT EXISTS registration_otp (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    email         TEXT NOT NULL,
    name          TEXT,
    surname       TEXT,
    password_hash TEXT NOT NULL,
    birthdate     DATE,
    birthplace    TEXT,
    code_hash     TEXT NOT NULL,
    expires_at    TIMESTAMPTZ NOT NULL,
    attempts      INT NOT NULL DEFAULT 0,
    created_at    TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE UNIQUE INDEX IF NOT EXISTS idx_registration_otp_email ON registration_otp (email);
