-- Challenge OTP di accesso (2FA via email). Una riga rappresenta l'OTP pendente di un utente:
-- creata dopo la validazione delle credenziali (AuthController.login), consumata alla verifica.
-- Il codice è salvato come hash BCrypt (mai in chiaro). Validità tipica 5 minuti (RAD: GENERA OTP).
--
-- Schema gestito a mano (spring.sql.init.mode=never, niente Flyway): esegui questo script
-- nello SQL Editor di Supabase, sul progetto a cui punta l'app.
--
-- NB: "user" è parola riservata in Postgres, va quotata. ON DELETE CASCADE: l'eliminazione
-- dell'utente rimuove anche l'eventuale OTP pendente. IF NOT EXISTS rende lo script idempotente.
CREATE TABLE IF NOT EXISTS login_otp (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_user     BIGINT NOT NULL REFERENCES "user"(id) ON DELETE CASCADE,
    code_hash   TEXT NOT NULL,
    expires_at  TIMESTAMPTZ NOT NULL,
    attempts    INT NOT NULL DEFAULT 0,
    created_at  TIMESTAMPTZ NOT NULL DEFAULT now()
);

-- Un solo OTP attivo per utente: la rigenerazione ("Riprova") sostituisce la riga esistente
-- (OtpService fa delete-then-insert). L'indice UNIQUE su id_user impone l'invariante.
CREATE UNIQUE INDEX IF NOT EXISTS idx_login_otp_user ON login_otp (id_user);
