spring.application.name=artid-server

# DataSource
spring.datasource.url=jdbc:postgresql://100.114.51.46:5432/artid
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver

# Connection pool (HikariCP)
spring.datasource.hikari.maximum-pool-size=10
spring.datasource.hikari.connection-timeout=20000

# JDBC
spring.sql.init.mode=never
